apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_DB
        image: uchechukwu/udagram-api-feed:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 400m
          requests:
              cpu: 200m
---

apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    run: backend-feed
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: backend-feed
        